<?php

namespace app\controllers;

use Yii;
use app\models\Lid;
use yii\bootstrap\ActiveForm;
use yii\web\Response;
use app\libs\Zoho_api;


class SiteController extends BasicController
{

    public $model;

    /**
     * Отрисовываем фомру
     *
     * @return string
     */
    public function actionIndex()
    {
        $this->model = new Lid();
        return $this->render('index');
    }

    /**
     * API запрос на содания лида
     *
     * @return array
     */
    public function actionCreate_lid()
    {
        $this->init_ajax();
        $model = new Lid();
        $model->load(Yii::$app->request->post());

        $this->error = 'no';

        //$model = ['name'=>'1 ','price'=>'12']; //тест заглушка
        $model_zoho = new Zoho_api(Yii::$app->params['api_zoho'],$model);

        //ищем в лида номер телефона
        //toDo по хорошему нужно сделать меод который будет приводить номера телефонов к кединому виду +7 (в зависимости от страны)
        $result = $model_zoho->find_lid_phone();

        //если найдено, тогда создаем сделку, в противном случае добавляем лид (предварительный контакт
        if (!$model_zoho->error && $result) {
            $this->msg = 'Создана сделка!';
        } else {
            $model_zoho->create_lid();
            $this->msg = 'Создан новый предварительный контакт (лид)!';
        }

        if ($model_zoho->error) {
            $this->error_conver($model_zoho);
        }

        return $this->out();
    }

    /**
     * Получение ошибок из библиотеки API_Zoho
     *
     * @param $model_zoho
     */
    public function error_conver($model_zoho)
    {
        $this->msg = $model_zoho->error_text;
        $this->error_type = $model_zoho->error_code;
        $this->error = 'yes';
    }

    /**
     * Ajax валидация формы
     *
     * @return array
     */
    public function actionValidate_form_lid()
    {
        $model = new Lid();

        if (Yii::$app->request->isAjax) {
            $model->load(Yii::$app->request->post());
            Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
        }
    }

    /**
     * Обработка ошибок
     *
     * @return array
     */
    public function actionError()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }
}
